# Below is the function for date column difference as asked in question 1

In [103]:
from dateutil.parser import parse 

def is_date(string, fuzzy=False):
    """
    Return whether the string can be interpreted as a date.

    """
    try: 
        parse(string, fuzzy=fuzzy)
        return True

    except ValueError:
        return False
        
def date_column_difference(dataset):
  dataset.dropna(inplace=True)
  total_rows=len(dataset.axes[0])
  c1=0
  l1,l2,l3,l4=[],[],[],[]

  for i in dataset.columns:
    l1=[]
    for k in range(total_rows):
      
      if dataset[i].dtypes=='object' and is_date(dataset[i][k])== True:
          #print(k,dataset[i][k])
          l1.append(dataset[i][k])
          c1+=1
    if len(l1)!=0:
      l2.append(l1)
  # for i in range(len(l2)):
  #   print(l2[i])

  for j in range(0,total_rows):
    l3=[]
    for i in range(0,round(c1/total_rows)):
      if i+1<round(c1/total_rows):
        start_date = datetime.strptime(l2[i][j], "%d-%b-%y")
        end_date = datetime.strptime(l2[i+1][j], "%d-%b-%y")
        l3.append(abs((end_date-start_date).days))
    l4.append(l3)
  # print(l4)
  l5=[]
  for i in range(round(c1/total_rows)-1):
    l5.append('Diff. of Column '+str(i+1))
  # print(l5)

  data = l4 

  df = pd.DataFrame(data, columns = l5) 

  result = pd.concat([dataset, df], axis=1)
  return result


#Below is the calling of function date_column_difference as asked in question 1

In [104]:
import pandas as pd
from datetime import datetime
dataset=pd.read_csv('dataset for Question 1.csv')

date_column_difference(dataset)

DATE1    NAME  ... Diff. of Column 3  Diff. of Column 4
0   29-Nov-17  PRATIK  ...                 0                148
1   05-Jul-17  ROUNAK  ...                 0                 10
2   18-Jul-17  PRATIK  ...                 0                 10
3   01-Aug-17  ROUNAK  ...                14                  4
4   16-Aug-17  PRATIK  ...                 0                  0
5   16-Aug-17  ROUNAK  ...                 0                  0
6   16-Aug-17  PRATIK  ...                 0                  0
7   16-Aug-17  ROUNAK  ...                 0                  0
8   16-Aug-17  PRATIK  ...                 4                  0
9   16-Aug-17  ROUNAK  ...                 0                  0
10  16-Aug-17  PRATIK  ...                 0                  0
11  16-Aug-17  ROUNAK  ...                 0                  0
12  16-Aug-17  PRATIK  ...                 0                  0
13  16-Aug-17  ROUNAK  ...                 0                  0
14  16-Aug-17  PRATIK  ...                 0                  0
15  16-Aug-17  ROUNAK  ...                 0                  0

[16 rows x 13 columns]

# Below is the function for removing the outlier as asked in question 2

In [105]:
def detect_outliers(data):
   
    import numpy as np
    outliers=[]

    threshold=3
    mean = np.mean(data)
    std =np.std(data)
    
    
    for i in data:
        z_score= (i - mean)/std 
        if np.abs(z_score) > threshold:
            outliers.append(i)
    return outliers

# Below is the calling of function for removing the outlier as asked in question 2

In [106]:
import pandas as pd
data=pd.read_csv('dataset for Question 2.csv')

for i in data.columns:
    if data[i].dtypes!='object':
        data[i].fillna(value=(data[i].mean()),inplace=True)
        data[i] = data[i].replace(0, data[i].mean())
        print(detect_outliers(data[i]))


[]
[8000.0]
[181]
[41.0]
[]
[5550.0]


#Below is the function for removing  columns having Pearson correlation more than 0.85 as asked in question 3

In [107]:
def corr1(df):
    import numpy as np

    # Create correlation matrix
    corr_matrix = df.corr(method ='pearson').abs()

    # Select upper triangle of correlation matrix
    upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape),k=1).astype(np.bool))
    
    # Find index of feature columns with correlation greater than 0.85
    to_drop = [column for column in upper.columns if any(upper[column] > 0.85)]
    
    # Drop Marked Features
    df1 = df.drop(df.columns[to_drop], axis=1)
    
    return(df1)

#Below is the calling of function for removing  columns having Pearson correlation more than 0.85 as asked in question 3

In [108]:
import pandas as pd
# data=pd.read_csv('dataset for Question 3.csv')

from sklearn.datasets import load_iris

iris = load_iris()

# Create features and target
X = iris.data; print(); print(X)
y = iris.target; print(); print(y)

# Convert feature matrix into DataFrame
data = pd.DataFrame(X)
corr1(data)


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4

0    1
0    5.1  3.5
1    4.9  3.0
2    4.7  3.2
3    4.6  3.1
4    5.0  3.6
..   ...  ...
145  6.7  3.0
146  6.3  2.5
147  6.5  3.0
148  6.2  3.4
149  5.9  3.0

[150 rows x 2 columns]